# Generated by Django 2.2.2 on 2019-06-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conveyor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('conveyor_speed', models.FloatField(default=0)),
                ('material_density', models.FloatField(default=0)),
                ('area', models.FloatField(default=0)),
                ('volume_sum', models.FloatField(default=0)),
                ('volume_stream', models.FloatField(default=0)),
                ('mass_sum', models.FloatField(default=0)),
                ('mass_stream', models.FloatField(default=0)),
                ('conveyor_deviation', models.FloatField(default=0)),
                ('count_valid_pts', models.FloatField(default=0)),
                ('total_area', models.FloatField(default=0)),
                ('volume_stream_upper_limit', models.FloatField(default=0)),
                ('volume_stream_lower_limit', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='volume',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='scanner',
        ),
        migrations.AddField(
            model_name='job',
            name='conveyor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Conveyor'),
        ),
        migrations.DeleteModel(
            name='Scanner',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
        migrations.AddField(
            model_name='measurement',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Job'),
        ),
    ]
