# Generated by Django 2.2.2 on 2019-07-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190626_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='volume_stream_lower_limit',
            new_name='lower_limit',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='volume_stream_upper_limit',
            new_name='upper_limit',
        ),
        migrations.RemoveField(
            model_name='job',
            name='belt_speed',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='total_area',
        ),
    ]
